name: AWS-EBS

on:
  push:
    branches:
    - master

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Generate deployment package
      run: zip deploy.zip *.*
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v4
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: taos-demo
        environment_name: TaosDemo-env
        version_label: 12345
        region: us-east-2
        deployment_package: deploy.zip
